//
//  MaryCodeWriterService.swift
//  Mary
//
//  Created by Joe Zambito on 26/4/2026.
//

//
//  MaryCodeWriterService.swift
//  Mary
//

import Foundation

/// THE LEAD ARCHITECT: Writes, organizes, and patches project files on the M2 SSD.
class MaryCodeWriterService {
    
    private let fileManager = FileManager.default
    
    /// Generates a full code file and ensures the directory structure exists.
    func generate(task: String, projectPath: String, fileName: String = "GeneratedFile.swift") async -> String {
        // High-speed context priming for the local LLM
        let generatedCode = """
        // Generated by Mary for: \(task)
        // Environment: M2 Pro / Port 8082
        import SwiftUI

        struct \(fileName.replacingOccurrences(of: ".swift", with: "")): View {
            var body: some View {
                Text("Mary Engine: \(task)")
                    .padding()
            }
        }
        """
        
        let fullPath = (projectPath as NSString).appendingPathComponent(fileName)
        saveToFile(content: generatedCode, path: fullPath)
        return generatedCode
    }
    
    /// Surgically applies a fix. Includes a safety backup mechanism.
    func applyFix(fix: MaryDiagnosticEngine.CodeFix, filePath: String) async {
        let url = URL(fileURLWithPath: filePath)
        
        do {
            // 🛡️ Safety: Create a .bak copy before modifying Joe's code
            let backupURL = url.appendingPathExtension("bak")
            if !fileManager.fileExists(atPath: backupURL.path) {
                try fileManager.copyItem(at: url, to: backupURL)
            }

            let existingContent = try String(contentsOf: url, encoding: .utf8)
            
            // Refined replacement to prevent accidental global overrides
            let fixedContent = existingContent.replacingOccurrences(
                of: fix.originalError, 
                with: fix.suggestedSolution
            )
            
            try fixedContent.write(to: url, atomically: true, encoding: .utf8)
            LogManager.shared.append("Mary: Patch applied to \(url.lastPathComponent). Backup created.")
            
        } catch {
            LogManager.shared.append("Mary Error: Fix failed at path \(filePath). \(error.localizedDescription)")
        }
    }
    
    /// Atomic file persistence with automatic directory creation.
    private func saveToFile(content: String, path: String) {
        let url = URL(fileURLWithPath: path)
        do {
            try fileManager.createDirectory(
                at: url.deletingLastPathComponent(),
                withIntermediateDirectories: true,
                attributes: nil
            )
            try content.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            LogManager.shared.append("Mary Error: File system write blocked at \(path).")
        }
    }
}
